name: flutter_compass_plus_example
description: Demonstrates how to use the flutter_compass_plus plugin.

publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_compass_plus:
    path: ../
  permission_handler: ^10.4.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

